import json
from io import BytesIO
from json import JSONDecodeError
from unittest.mock import MagicMock, sentinel

import pytest
from h_matchers import Any
from requests import Response

from tests.factories import TranscriptInfoFactory
from via.services.youtube_transcript import (
    TranscriptInfo,
    YouTubeTranscriptService,
    factory,
)


class TestTranscriptInfo:
    @pytest.mark.parametrize(
        "transcript_info,expected_id",  # noqa: PT006
        [
            (
                TranscriptInfoFactory(),
                "en-us..RW5nbGlzaCAoVW5pdGVkIFN0YXRlcyk=",
            ),
            (
                TranscriptInfoFactory(autogenerated=True),
                "en-us.a.RW5nbGlzaCAoVW5pdGVkIFN0YXRlcyk=",
            ),
        ],
    )
    def test_id(self, transcript_info, expected_id):
        assert transcript_info.id == expected_id


class TestYouTubeTranscriptService:
    def test_get_transcript_infos(self, svc, http_service):
        # The JSON response body from the Supadata API.
        response_json = {
            "lang": "en",
            "availableLangs": ["en", "en-US"],
            "content": [{"text": "Hello", "offset": 0, "duration": 1000}],
        }
        response = http_service.get.return_value = Response()
        response.status_code = 200
        response.json = lambda: response_json
        response.raw = BytesIO(json.dumps(response_json).encode("utf-8"))

        transcript_infos = svc.get_transcript_infos("test_video_id")

        http_service.get.assert_called_once_with(
            "https://api.supadata.ai/v1/transcript",
            params={"url": "https://youtu.be/test_video_id"},
            headers={"x-api-key": "test_api_key"},
        )
        assert transcript_infos == [
            Any.instance_of(TranscriptInfo).with_attrs(
                {
                    "language_code": "en",
                    "autogenerated": False,
                    "name": "English",
                    "url": "supadata://test_video_id/en",
                }
            ),
            Any.instance_of(TranscriptInfo).with_attrs(
                {
                    "language_code": "en-us",
                    "autogenerated": False,
                    "name": "English (United States)",
                    "url": "supadata://test_video_id/en-US",
                }
            ),
        ]

    def test_get_transcript_infos_error_response(self, svc, http_service):
        # We get an error response from the Supadata API.
        http_service.get.side_effect = Exception("Something went wrong")

        with pytest.raises(Exception, match="Something went wrong"):
            svc.get_transcript_infos("test_video_id")

    @pytest.mark.parametrize(
        "response_body,exception_class",  # noqa: PT006
        [
            (b"foo", JSONDecodeError),  # Not valid JSON.
            (b"[]", AttributeError),  # Not a dict (no .get method).
        ],
    )
    def test_get_transcript_infos_unexpected_response(
        self, svc, http_service, response_body, exception_class
    ):
        """It crashes if the response body isn't what we expect."""
        response = http_service.get.return_value = Response()
        response.status_code = 200
        response.encoding = "utf-8"
        response.raw = BytesIO(response_body)

        # Configure json() to parse the response_body when called
        # This will raise JSONDecodeError for invalid JSON, or return the parsed value
        def json_method():
            return json.loads(response_body.decode("utf-8"))

        response.json = json_method

        with pytest.raises(exception_class):
            svc.get_transcript_infos("test_video_id")

    @pytest.mark.parametrize(
        "transcript_infos,expected_default_transcript_index",  # noqa: PT006
        [
            (
                [
                    TranscriptInfoFactory(language_code="en", name="English"),
                    TranscriptInfoFactory(
                        language_code="en-us", name="English (United States)"
                    ),
                ],
                0,
            ),
            (
                [
                    TranscriptInfoFactory(
                        language_code="en-us", name="English (United States)"
                    ),
                    TranscriptInfoFactory(language_code="en", name="English - DTVCC1"),
                ],
                0,
            ),
            (
                [
                    TranscriptInfoFactory(language_code="en", name="English - Foo"),
                    TranscriptInfoFactory(
                        language_code="en-us", name="English (United States) - Foo"
                    ),
                ],
                0,
            ),
            (
                [
                    TranscriptInfoFactory(
                        language_code="en-us", name="English (United States) - Foo"
                    ),
                    TranscriptInfoFactory(
                        language_code="en", name="English", autogenerated=True
                    ),
                ],
                0,
            ),
            (
                [
                    TranscriptInfoFactory(
                        language_code="en", name="English", autogenerated=True
                    ),
                    TranscriptInfoFactory(
                        language_code="en-us",
                        name="English (United States)",
                        autogenerated=True,
                    ),
                ],
                0,
            ),
            (
                [
                    TranscriptInfoFactory(language_code="fr", name="French"),
                    TranscriptInfoFactory(
                        language_code="en", name="English", autogenerated=True
                    ),
                ],
                1,
            ),
            (
                [
                    TranscriptInfoFactory(language_code="fr", name="French"),
                    TranscriptInfoFactory(language_code="de", name="Deutsch"),
                ],
                0,
            ),
        ],
    )
    def test_pick_default_transcript(
        self, svc, transcript_infos, expected_default_transcript_index
    ):
        assert (
            svc.pick_default_transcript(transcript_infos)
            == transcript_infos[expected_default_transcript_index]
        )

    def test_get_transcript(self, svc, transcript_info, http_service):
        response_json = {
            "lang": "en-US",
            "content": [
                {"text": "Hey there guys,", "offset": 210, "duration": 1387},
                {"text": "Lichen' subscribe", "offset": 1597, "duration": 0},
                {"text": "Buy my merch!", "offset": 4327, "duration": 2063},
            ],
        }
        response = http_service.get.return_value = Response()
        response.status_code = 200
        response.json = lambda: response_json
        response.raw = BytesIO(json.dumps(response_json).encode("utf-8"))

        transcript = svc.get_transcript(transcript_info)
        http_service.get.assert_called_once_with(
            "https://api.supadata.ai/v1/transcript",
            params={
                "url": "https://youtu.be/test_video_id",
                "lang": "en-US",
            },
            headers={"x-api-key": "test_api_key"},
        )

        assert transcript == [
            {"duration": 1.387, "start": 0.21, "text": "Hey there guys,"},
            {"duration": 0.0, "start": 1.597, "text": "Lichen' subscribe"},
            {"duration": 2.063, "start": 4.327, "text": "Buy my merch!"},
        ]

    def test_get_transcript_error_response(self, svc, transcript_info, http_service):
        # We get an error response from the Supadata API.
        http_service.get.side_effect = Exception("Something went wrong")

        with pytest.raises(Exception, match="Something went wrong"):
            svc.get_transcript(transcript_info)

    def test_get_transcript_unexpected_response(
        self, svc, transcript_info, http_service
    ):
        response = http_service.get.return_value = Response()
        response.status_code = 200
        response.json = lambda: "not a dict"

        with pytest.raises((TypeError, AttributeError)):
            svc.get_transcript(transcript_info)

    @pytest.fixture
    def transcript_info(self):
        return TranscriptInfo(
            language_code="en-us",
            name="English (United States)",
            url="supadata://test_video_id/en-US",
            autogenerated=False,
        )

    @pytest.fixture
    def svc(self, http_service):
        return YouTubeTranscriptService(http_service, api_key="test_api_key")


class TestFactory:
    def test_factory(self, YouTubeTranscriptService, pyramid_request, HTTPService):
        svc = factory(sentinel.context, pyramid_request)

        HTTPService.assert_called_once()

        YouTubeTranscriptService.assert_called_once_with(
            http_service=HTTPService.return_value,
            api_key="test_supadata_api_key",
        )

        assert svc == YouTubeTranscriptService.return_value

    @pytest.fixture
    def HTTPService(self, patch):
        return patch("via.services.youtube_transcript.HTTPService")

    @pytest.fixture
    def YouTubeTranscriptService(self, patch):
        return patch("via.services.youtube_transcript.YouTubeTranscriptService")


@pytest.fixture
def http_service():
    return MagicMock(spec_set=["get"])
