from factory import Factory, Sequence

from via.services.youtube_transcript import TranscriptInfo


class TranscriptInfoFactory(Factory):
    class Meta:
        model = TranscriptInfo

    language_code = "en-us"
    name = "English (United States)"
    url = Sequence(lambda n: f"https://example.com/api/timedtext?v={n}")
    autogenerated = False
