name: Continuous integration

on:
  pull_request:
    paths-ignore:
      - '.cookiecutter/*'
      - 'docs/*'
      - 'requirements/*.in'
      - 'requirements/dev.txt'
      - '**/.gitignore'
      - '*.md'
      - 'LICENSE'
  workflow_call:

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      TOX_PARALLEL_NO_SPINNER: 1

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install tox
      run: python -m pip install 'tox<4'

    - name: Cache the .tox dir
      uses: actions/cache@v3
      with:
        path: .tox
        key: ${{ runner.os }}-tox-${{ hashFiles('tox.ini', 'requirements*', 'setup.py', 'setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-tox-

    - name: Run tox
      run: tox --parallel -e lint,checkformatting,tests,coverage,functests
