name: Frontend
on:
  workflow_dispatch:
  workflow_call:
jobs:
  Frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache the node_modules dir
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

    - name: Install
      run: yarn install --frozen-lockfile && yarn playwright install chromium

    - name: Format
      run: yarn checkformatting

    - name: Lint
      run: yarn lint

    - name: Typecheck
      run: yarn typecheck

    - name: Test
      run: yarn test
