# Redeploy the currently deployed version of Via, a.k.a "turn if off and on again".
name: Redeploy
concurrency:
  group: ${{ github.event.repository.name }}-deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
jobs:
  QA:
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA
      github_environment_url: https://qa-via.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: via
      elasticbeanstalk_environment: qa
    secrets: inherit
  QA (Edu):
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA (Edu)
      github_environment_url: https://qa-lms-via.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: lms-via
      elasticbeanstalk_environment: qa
    secrets: inherit
  Production:
    needs: QA
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production
      github_environment_url: https://via.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: via
      elasticbeanstalk_environment: prod
    secrets: inherit
  Production (Edu):
    needs: QA (Edu)
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (Edu)
      github_environment_url: https://lms-via.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: lms-via
      elasticbeanstalk_environment: prod
    secrets: inherit
