name: Redeploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      qa:
        type: boolean
        description: Redeploy QA
      QA_Edu:
        type: boolean
        description: Redeploy QA (Edu)
      production:
        type: boolean
        description: Redeploy Production
      production_edu:
        type: boolean
        description: Redeploy Production (Edu)
jobs:
  qa:
    name: QA
    if: inputs.qa
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA
      github_environment_url: https://qa-via.hypothes.is/https://en.wikipedia.org/api/rest_v1/page/pdf/Comet_Kohoutek
      aws_region: us-west-1
      elasticbeanstalk_application: via
      elasticbeanstalk_environment: qa
    secrets: inherit
  QA_Edu:
    name: QA (Edu)
    if: inputs.QA_Edu
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA (Edu)
      github_environment_url: https://hypothesis.instructure.com/courses/125/assignments/878
      aws_region: us-west-1
      elasticbeanstalk_application: lms-via
      elasticbeanstalk_environment: qa
    secrets: inherit
  production:
    name: Production
    if: inputs.production
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production
      github_environment_url: https://via.hypothes.is/https://en.wikipedia.org/api/rest_v1/page/pdf/Comet_Kohoutek
      aws_region: us-west-1
      elasticbeanstalk_application: via
      elasticbeanstalk_environment: prod
    secrets: inherit
  production_edu:
    name: Production (Edu)
    if: inputs.production_edu
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (Edu)
      github_environment_url: https://hypothesis.instructure.com/courses/125/assignments/882
      aws_region: us-west-1
      elasticbeanstalk_application: lms-via
      elasticbeanstalk_environment: prod
    secrets: inherit
